// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCS8f3FtJn9T_XiypSgt7kD0coWS5mCEIc',
    appId: '1:106653343525:web:c69cc6157f6a919a7004cc',
    messagingSenderId: '106653343525',
    projectId: 'attendence-managment-sys-4cc8f',
    authDomain: 'attendence-managment-sys-4cc8f.firebaseapp.com',
    storageBucket: 'attendence-managment-sys-4cc8f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAg-SPBHQPDQ3SkivkzkBjth-L7ZY6LTzE',
    appId: '1:106653343525:android:0587028d28d0197a7004cc',
    messagingSenderId: '106653343525',
    projectId: 'attendence-managment-sys-4cc8f',
    storageBucket: 'attendence-managment-sys-4cc8f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHALBmJyx0zKuhMMdIVSdFbpwiw7SNC-c',
    appId: '1:106653343525:ios:bb59677032ac709a7004cc',
    messagingSenderId: '106653343525',
    projectId: 'attendence-managment-sys-4cc8f',
    storageBucket: 'attendence-managment-sys-4cc8f.appspot.com',
    iosBundleId: 'com.example.attendenceManagSys',
  );
}
